FROM node:20-alpine as builder

WORKDIR /app

COPY app/routing-app/package*.json ./
RUN npm ci

COPY app/routing-app .

RUN npm run build

FROM node:20-alpine

WORKDIR /app
RUN npm install -g serve@14.2.3

COPY --from=builder /app/dist dist

EXPOSE 5174

CMD ["serve", "-s", "dist", "-l", "5174"]
